<?php
namespace Yeriomin\ConsoleApp;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 05:04:11.
 */
class ConsoleAppTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConsoleApp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include_once dirname(__FILE__) . '/ConsoleAppMock.php';
        $this->object = new ConsoleAppMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::unlock
     * @todo   Implement testUnlock().
     */
    public function testUnlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::signalHandler
     * @todo   Implement testSignalHandler().
     */
    public function testSignalHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::errorHandler
     * @todo   Implement testErrorHandler().
     */
    public function testErrorHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::setLogger
     * @todo   Implement testSetLogger().
     */
    public function testSetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
