<?php
namespace Yeriomin\ConsoleApp;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 05:04:11.
 */
class ConsoleAppTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConsoleApp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include_once dirname(__FILE__) . '/ConsoleAppMock.php';
        //$this->object = new ConsoleAppMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * Call protected/private method of a class.
     *
     * @param object &$object    Instantiated object that we will run method on.
     * @param string $methodName Method name to call
     * @param array  $parameters Array of parameters to pass into method.
     *
     * @return mixed Method return.
     */
    public function invokeMethod(&$object, $methodName, array $parameters = array())
    {
        $reflection = new \ReflectionClass(get_class($object));
        $method = $reflection->getMethod($methodName);
        $method->setAccessible(true);

        return $method->invokeArgs($object, $parameters);
    }

    /**
     * @covers Yeriomin\ConsoleApp\ConsoleApp::setLogger
     * @todo   Implement testSetLogger().
     */
    public function testSetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
